print("You feelings are valid and you are valued.")
vim.cmd.colorscheme('torte')
vim.keymap.set('n', 'äwhore', function() print("press me harder daddy :3") end)
vim.keymap.set('n', 'j','gj')
vim.keymap.set('n', 'k','gk')
vim.keymap.set('n', 'äc', ':!gcc -Wall -Wextra -Werror -Wpedantic *.c<Return>')
vim.keymap.set('n', 'ätc', ':tabnew<Return>')
vim.keymap.set('n', 'ätn', ':tabnext<Return>')
vim.keymap.set('n', 'ätp', ':tabprevious<Return>')
